"""Scenario-based practice data for HTTP status code training."""

SCENARIOS = [
    # --- Beginner (8 scenarios) ---
    {
        "id": 1,
        "difficulty": "beginner",
        "description": "You send a GET request to fetch a user's profile, and the server returns the data successfully. What status code should the server return?",
        "correct": "200",
        "options": ["200", "201", "204", "302"],
        "explanations": {
            "200": "Correct! 200 OK is the standard response for a successful GET request that returns data.",
            "201": "201 Created is for when a new resource has been created, not for fetching existing data.",
            "204": "204 No Content means success but with no body — not appropriate when returning profile data.",
            "302": "302 Found is a redirect, not a successful data response.",
        },
    },
    {
        "id": 2,
        "difficulty": "beginner",
        "description": "A user tries to access a page that doesn't exist on your website. What status code should you return?",
        "correct": "404",
        "options": ["404", "400", "410", "403"],
        "explanations": {
            "404": "Correct! 404 Not Found means the server can't find the requested resource.",
            "400": "400 Bad Request means the request itself was malformed, not that the resource is missing.",
            "410": "410 Gone means the resource existed before but has been permanently removed. 404 is better when you don't know if it ever existed.",
            "403": "403 Forbidden means the resource exists but the user isn't allowed to access it.",
        },
    },
    {
        "id": 3,
        "difficulty": "beginner",
        "description": "Your API receives a POST request to create a new blog post, and the post is created successfully. What status code should you return?",
        "correct": "201",
        "options": ["201", "200", "202", "204"],
        "explanations": {
            "201": "Correct! 201 Created is the proper response when a new resource has been successfully created.",
            "200": "200 OK works but doesn't specifically communicate that a new resource was created.",
            "202": "202 Accepted means the request was received but the resource hasn't been created yet (async processing).",
            "204": "204 No Content means success with no body — but after creating a resource you'd typically return it.",
        },
    },
    {
        "id": 4,
        "difficulty": "beginner",
        "description": "A user sends a request but forgets to include a required 'email' field in the JSON body. What status code should your API return?",
        "correct": "400",
        "options": ["400", "404", "422", "500"],
        "explanations": {
            "400": "Correct! 400 Bad Request indicates the client sent a malformed or invalid request.",
            "404": "404 Not Found is for missing resources, not invalid request data.",
            "422": "422 Unprocessable Entity is also valid for validation errors, but 400 is the more general and widely-used choice.",
            "500": "500 Internal Server Error implies the server broke — but this is a client mistake, not a server bug.",
        },
    },
    {
        "id": 5,
        "difficulty": "beginner",
        "description": "Your server crashes while processing a request due to an unhandled exception. What status code should be returned?",
        "correct": "500",
        "options": ["500", "502", "503", "400"],
        "explanations": {
            "500": "Correct! 500 Internal Server Error is the generic response when the server encounters an unexpected condition.",
            "502": "502 Bad Gateway means a gateway or proxy received an invalid response from an upstream server.",
            "503": "503 Service Unavailable means the server is temporarily overloaded or under maintenance — not the same as a crash.",
            "400": "400 Bad Request blames the client, but the error is on the server side.",
        },
    },
    {
        "id": 6,
        "difficulty": "beginner",
        "description": "A user tries to access an admin panel without logging in first. What status code should your API return?",
        "correct": "401",
        "options": ["401", "403", "404", "400"],
        "explanations": {
            "401": "Correct! 401 Unauthorized means the request lacks valid authentication credentials.",
            "403": "403 Forbidden means the server knows who you are but you're not allowed. 401 is for when you haven't authenticated at all.",
            "404": "404 Not Found could be used to hide the endpoint's existence, but 401 is the semantically correct choice.",
            "400": "400 Bad Request is for malformed requests, not authentication issues.",
        },
    },
    {
        "id": 7,
        "difficulty": "beginner",
        "description": "Your website has moved permanently to a new domain (from http to https). What status code should you use for the redirect?",
        "correct": "301",
        "options": ["301", "302", "307", "308"],
        "explanations": {
            "301": "Correct! 301 Moved Permanently tells clients and search engines that the resource has permanently moved to a new URL.",
            "302": "302 Found is a temporary redirect — not appropriate for a permanent domain migration.",
            "307": "307 Temporary Redirect preserves the HTTP method but is temporary, not permanent.",
            "308": "308 Permanent Redirect preserves the HTTP method. 301 is more traditional for domain migrations, though 308 is also acceptable.",
        },
    },
    {
        "id": 8,
        "difficulty": "beginner",
        "description": "A user successfully deletes their account via a DELETE request, and there's no additional data to return. What status code is most appropriate?",
        "correct": "204",
        "options": ["204", "200", "202", "404"],
        "explanations": {
            "204": "Correct! 204 No Content means the action was successful and there's nothing to send back in the response body.",
            "200": "200 OK works if you return a confirmation message, but 204 is more appropriate when there's no response body.",
            "202": "202 Accepted would mean the deletion is queued but not yet completed.",
            "404": "404 Not Found would mean the account doesn't exist — but it did exist and was successfully deleted.",
        },
    },
    # --- Intermediate (9 scenarios) ---
    {
        "id": 9,
        "difficulty": "intermediate",
        "description": "You're building a REST API. A user sends a DELETE request for a resource that was already deleted last week. What should you return?",
        "correct": "404",
        "options": ["404", "410", "204", "409"],
        "explanations": {
            "404": "Correct! 404 Not Found is the standard response — the resource doesn't exist. Unless you specifically track deletions, 404 is appropriate.",
            "410": "410 Gone is more specific and tells the client the resource was intentionally deleted. This is valid if you track deletion history, but 404 is more common.",
            "204": "204 No Content would imply the DELETE succeeded, but you shouldn't confirm deletion of something already gone.",
            "409": "409 Conflict is for state conflicts during an operation, not for missing resources.",
        },
    },
    {
        "id": 10,
        "difficulty": "intermediate",
        "description": "Your API receives a PUT request to update a user's email, but another request is simultaneously updating the same user. The requests conflict. What status code should you return?",
        "correct": "409",
        "options": ["409", "400", "423", "500"],
        "explanations": {
            "409": "Correct! 409 Conflict indicates the request conflicts with the current state of the resource.",
            "400": "400 Bad Request implies the request itself is malformed — but the request is valid, it's the timing that's the problem.",
            "423": "423 Locked is a WebDAV status for when a resource is locked — close, but 409 is more appropriate for general conflict scenarios.",
            "500": "500 Internal Server Error implies an unexpected crash, but this is an expected concurrency issue that should be handled gracefully.",
        },
    },
    {
        "id": 11,
        "difficulty": "intermediate",
        "description": "A client sends a request with an Authorization header, but the token has expired. The user needs to re-authenticate. What should you return?",
        "correct": "401",
        "options": ["401", "403", "419", "400"],
        "explanations": {
            "401": "Correct! 401 Unauthorized means the credentials are invalid or expired. The client should re-authenticate.",
            "403": "403 Forbidden means the server understands the request but refuses to authorize it — different from expired credentials.",
            "419": "419 is not a standard HTTP status code. Some frameworks use it for session expiry, but 401 is the correct standard code.",
            "400": "400 Bad Request is for malformed requests, not for authentication/authorization issues.",
        },
    },
    {
        "id": 12,
        "difficulty": "intermediate",
        "description": "Your API supports JSON only, but a client sends a request with Content-Type: application/xml. What status code should you return?",
        "correct": "415",
        "options": ["415", "400", "406", "422"],
        "explanations": {
            "415": "Correct! 415 Unsupported Media Type means the server refuses to accept the request because the payload format is not supported.",
            "400": "400 Bad Request is too generic — 415 precisely communicates the issue is with the content type.",
            "406": "406 Not Acceptable is about the server not being able to produce a response matching the client's Accept header, not about the request body format.",
            "422": "422 Unprocessable Entity is for valid syntax but semantic errors in the body, not the wrong media type entirely.",
        },
    },
    {
        "id": 13,
        "difficulty": "intermediate",
        "description": "A client sends a GET request with an If-None-Match header, and the ETag matches the current version. The resource hasn't changed. What should you return?",
        "correct": "304",
        "options": ["304", "200", "204", "412"],
        "explanations": {
            "304": "Correct! 304 Not Modified tells the client to use its cached copy — the resource hasn't changed since last fetched.",
            "200": "200 OK with the full body would work but wastes bandwidth. 304 is designed exactly for this caching scenario.",
            "204": "204 No Content means success with no body, but it doesn't convey the caching semantics that 304 does.",
            "412": "412 Precondition Failed is for when conditions in headers like If-Match fail, not If-None-Match cache checks.",
        },
    },
    {
        "id": 14,
        "difficulty": "intermediate",
        "description": "Your server is undergoing scheduled maintenance and will be back in 2 hours. What status code should you return to all incoming requests?",
        "correct": "503",
        "options": ["503", "500", "502", "504"],
        "explanations": {
            "503": "Correct! 503 Service Unavailable indicates the server is temporarily unable to handle requests, often due to maintenance. Include a Retry-After header!",
            "500": "500 Internal Server Error implies an unexpected crash, not planned maintenance.",
            "502": "502 Bad Gateway means a proxy received an invalid response from upstream — not the same as planned downtime.",
            "504": "504 Gateway Timeout means a proxy didn't get a timely response from upstream — not relevant to maintenance.",
        },
    },
    {
        "id": 15,
        "difficulty": "intermediate",
        "description": "A logged-in regular user tries to access the admin-only settings page. They are authenticated but don't have admin privileges. What should you return?",
        "correct": "403",
        "options": ["403", "401", "404", "405"],
        "explanations": {
            "403": "Correct! 403 Forbidden means the server knows who the user is but they don't have permission to access this resource.",
            "401": "401 Unauthorized is for missing or invalid authentication. This user IS authenticated, just not authorized.",
            "404": "404 Not Found could be used to hide the endpoint from unauthorized users, but 403 is semantically correct.",
            "405": "405 Method Not Allowed is about using the wrong HTTP method (e.g., POST instead of GET), not about permissions.",
        },
    },
    {
        "id": 16,
        "difficulty": "intermediate",
        "description": "A client makes too many API requests and hits your rate limit. What status code should you return?",
        "correct": "429",
        "options": ["429", "403", "503", "400"],
        "explanations": {
            "429": "Correct! 429 Too Many Requests tells the client they've sent too many requests in a given time period. Include a Retry-After header.",
            "403": "403 Forbidden could work but doesn't communicate that the issue is rate limiting specifically.",
            "503": "503 Service Unavailable implies the whole service is down, not just that one client is being throttled.",
            "400": "400 Bad Request implies something is wrong with the request itself, not with how many requests were sent.",
        },
    },
    {
        "id": 17,
        "difficulty": "intermediate",
        "description": "Your API receives a long-running report generation request. You want to acknowledge receipt and process it in the background. What status code should you return?",
        "correct": "202",
        "options": ["202", "200", "201", "204"],
        "explanations": {
            "202": "Correct! 202 Accepted means the request has been accepted for processing, but the processing is not yet complete.",
            "200": "200 OK implies the request is fully completed — misleading for an async operation that hasn't finished yet.",
            "201": "201 Created implies the resource is already created, but it's still being generated.",
            "204": "204 No Content doesn't communicate that something is happening in the background.",
        },
    },
    # --- Expert (8 scenarios) ---
    {
        "id": 18,
        "difficulty": "expert",
        "description": "You're implementing a file upload endpoint. A client sends a POST request with a Content-Length of 50GB, which exceeds your server's limit. What status code should you return before the client finishes uploading?",
        "correct": "413",
        "options": ["413", "400", "507", "431"],
        "explanations": {
            "413": "Correct! 413 Payload Too Large tells the client the request body exceeds the server's defined limit.",
            "400": "400 Bad Request is too generic and doesn't tell the client specifically that the payload is too large.",
            "507": "507 Insufficient Storage is a WebDAV status about the server running out of storage — different from rejecting a too-large request.",
            "431": "431 Request Header Fields Too Large is about headers being too large, not the request body.",
        },
    },
    {
        "id": 19,
        "difficulty": "expert",
        "description": "A client sends a PATCH request to update a resource, but uses the If-Match header with an outdated ETag. The resource has been modified since the client last fetched it. What should you return?",
        "correct": "412",
        "options": ["412", "409", "304", "428"],
        "explanations": {
            "412": "Correct! 412 Precondition Failed means the condition specified in the If-Match header evaluated to false — the ETag doesn't match.",
            "409": "409 Conflict is for logical conflicts in the request, but 412 is specifically designed for conditional request failures.",
            "304": "304 Not Modified is for cache validation with If-None-Match on GET requests, not for conditional writes.",
            "428": "428 Precondition Required means the server requires a conditional request — but the client DID send one, it just failed.",
        },
    },
    {
        "id": 20,
        "difficulty": "expert",
        "description": "Your reverse proxy receives a request and forwards it to the backend server, but the backend returns a malformed HTTP response. What status code should the proxy return to the client?",
        "correct": "502",
        "options": ["502", "500", "503", "504"],
        "explanations": {
            "502": "Correct! 502 Bad Gateway means the proxy received an invalid response from the upstream server.",
            "500": "500 Internal Server Error implies the proxy itself crashed, not that it received a bad upstream response.",
            "503": "503 Service Unavailable means the service is temporarily down — not that an invalid response was received.",
            "504": "504 Gateway Timeout means the upstream server didn't respond in time — but here it did respond, just with garbage.",
        },
    },
    {
        "id": 21,
        "difficulty": "expert",
        "description": "A client sends a request to your API which only accepts GET and POST, but they use a PUT method. What status code should you return?",
        "correct": "405",
        "options": ["405", "400", "404", "501"],
        "explanations": {
            "405": "Correct! 405 Method Not Allowed means the HTTP method is not supported for this endpoint. Include an Allow header listing valid methods.",
            "400": "400 Bad Request implies the request is malformed, but the issue is specifically the HTTP method.",
            "404": "404 Not Found implies the URL doesn't exist — but it does, just not for PUT.",
            "501": "501 Not Implemented means the server doesn't support the method at all (for any endpoint), not just this specific resource.",
        },
    },
    {
        "id": 22,
        "difficulty": "expert",
        "description": "You're implementing WebSocket support. A client sends an HTTP/1.1 Upgrade request with Connection: Upgrade and Upgrade: websocket, and your server accepts the protocol switch. What status code should you return?",
        "correct": "101",
        "options": ["101", "200", "426", "100"],
        "explanations": {
            "101": "Correct! 101 Switching Protocols indicates the server is switching to the protocol specified in the Upgrade header (WebSocket).",
            "200": "200 OK doesn't indicate a protocol switch is happening — the client would remain on HTTP.",
            "426": "426 Upgrade Required means the server DEMANDS a protocol upgrade, not that it's accepting one.",
            "100": "100 Continue tells the client to proceed with the request body, not that a protocol switch is occurring.",
        },
    },
    {
        "id": 23,
        "difficulty": "expert",
        "description": "A government orders you to take down a specific page due to a legal demand. You want to communicate to users that the content was removed for legal reasons. What status code is most appropriate?",
        "correct": "451",
        "options": ["451", "403", "410", "404"],
        "explanations": {
            "451": "Correct! 451 Unavailable For Legal Reasons (named after Fahrenheit 451) indicates the resource is unavailable due to legal demands.",
            "403": "403 Forbidden is generic and doesn't explain WHY access is denied.",
            "410": "410 Gone means the resource was removed but doesn't communicate the legal reason.",
            "404": "404 Not Found pretends the resource never existed — 451 is more transparent about censorship.",
        },
    },
    {
        "id": 24,
        "difficulty": "expert",
        "description": "Your API requires all write requests to include an If-Match header for optimistic concurrency control, but a client sends a PUT request without it. What should you return?",
        "correct": "428",
        "options": ["428", "412", "400", "409"],
        "explanations": {
            "428": "Correct! 428 Precondition Required tells the client that the server requires the request to be conditional (include If-Match).",
            "412": "412 Precondition Failed is for when a precondition WAS sent but evaluated to false. Here, no precondition was sent at all.",
            "400": "400 Bad Request is too generic — 428 specifically communicates that a conditional header is required.",
            "409": "409 Conflict is for request conflicts with the current resource state, not for missing conditional headers.",
        },
    },
    {
        "id": 25,
        "difficulty": "expert",
        "description": "A client requests a range of bytes from a large video file using the Range header, but the requested range is beyond the end of the file. What status code should you return?",
        "correct": "416",
        "options": ["416", "400", "404", "206"],
        "explanations": {
            "416": "Correct! 416 Range Not Satisfiable means the range specified in the Range header can't be fulfilled — it's outside the resource's bounds.",
            "400": "400 Bad Request is too vague — 416 specifically addresses invalid range requests.",
            "404": "404 Not Found means the resource doesn't exist — but it does, the requested byte range is just invalid.",
            "206": "206 Partial Content is the success response for a valid range request, not for an invalid range.",
        },
    },
]
