"""Scenario-based practice data for HTTP status code training."""

SCENARIOS = [
    # --- Beginner (16 scenarios) ---
    {
        "id": 1,
        "difficulty": "beginner",
        "category": "crud",
        "description": "You send a GET request to fetch a user's profile, and the server returns the data successfully. What status code should the server return?",
        "correct": "200",
        "options": ["200", "201", "204", "302"],
        "explanations": {
            "200": "Correct! 200 OK is the standard response for a successful GET request that returns data.",
            "201": "201 Created is for when a new resource has been created, not for fetching existing data.",
            "204": "204 No Content means success but with no body — not appropriate when returning profile data.",
            "302": "302 Found is a redirect, not a successful data response.",
        },
    },
    {
        "id": 2,
        "difficulty": "beginner",
        "category": "errors",
        "description": "A user tries to access a page that doesn't exist on your website. What status code should you return?",
        "correct": "404",
        "options": ["404", "400", "410", "403"],
        "explanations": {
            "404": "Correct! 404 Not Found means the server can't find the requested resource.",
            "400": "400 Bad Request means the request itself was malformed, not that the resource is missing.",
            "410": "410 Gone means the resource existed before but has been permanently removed. 404 is better when you don't know if it ever existed.",
            "403": "403 Forbidden means the resource exists but the user isn't allowed to access it.",
        },
    },
    {
        "id": 3,
        "difficulty": "beginner",
        "category": "crud",
        "description": "Your API receives a POST request to create a new blog post, and the post is created successfully. What status code should you return?",
        "correct": "201",
        "options": ["201", "200", "202", "204"],
        "explanations": {
            "201": "Correct! 201 Created is the proper response when a new resource has been successfully created.",
            "200": "200 OK works but doesn't specifically communicate that a new resource was created.",
            "202": "202 Accepted means the request was received but the resource hasn't been created yet (async processing).",
            "204": "204 No Content means success with no body — but after creating a resource you'd typically return it.",
        },
    },
    {
        "id": 4,
        "difficulty": "beginner",
        "category": "errors",
        "description": "A user sends a request but forgets to include a required 'email' field in the JSON body. What status code should your API return?",
        "correct": "400",
        "options": ["400", "404", "422", "500"],
        "explanations": {
            "400": "Correct! 400 Bad Request indicates the client sent a malformed or invalid request.",
            "404": "404 Not Found is for missing resources, not invalid request data.",
            "422": "422 Unprocessable Entity is also valid for validation errors, but 400 is the more general and widely-used choice.",
            "500": "500 Internal Server Error implies the server broke — but this is a client mistake, not a server bug.",
        },
    },
    {
        "id": 5,
        "difficulty": "beginner",
        "category": "errors",
        "description": "Your server crashes while processing a request due to an unhandled exception. What status code should be returned?",
        "correct": "500",
        "options": ["500", "502", "503", "400"],
        "explanations": {
            "500": "Correct! 500 Internal Server Error is the generic response when the server encounters an unexpected condition.",
            "502": "502 Bad Gateway means a gateway or proxy received an invalid response from an upstream server.",
            "503": "503 Service Unavailable means the server is temporarily overloaded or under maintenance — not the same as a crash.",
            "400": "400 Bad Request blames the client, but the error is on the server side.",
        },
    },
    {
        "id": 6,
        "difficulty": "beginner",
        "category": "auth",
        "description": "A user tries to access an admin panel without logging in first. What status code should your API return?",
        "correct": "401",
        "options": ["401", "403", "404", "400"],
        "explanations": {
            "401": "Correct! 401 Unauthorized means the request lacks valid authentication credentials.",
            "403": "403 Forbidden means the server knows who you are but you're not allowed. 401 is for when you haven't authenticated at all.",
            "404": "404 Not Found could be used to hide the endpoint's existence, but 401 is the semantically correct choice.",
            "400": "400 Bad Request is for malformed requests, not authentication issues.",
        },
    },
    {
        "id": 7,
        "difficulty": "beginner",
        "category": "redirects",
        "description": "Your website has moved permanently to a new domain (from http to https). What status code should you use for the redirect?",
        "correct": "301",
        "options": ["301", "302", "307", "308"],
        "explanations": {
            "301": "Correct! 301 Moved Permanently tells clients and search engines that the resource has permanently moved to a new URL.",
            "302": "302 Found is a temporary redirect — not appropriate for a permanent domain migration.",
            "307": "307 Temporary Redirect preserves the HTTP method but is temporary, not permanent.",
            "308": "308 Permanent Redirect preserves the HTTP method. 301 is more traditional for domain migrations, though 308 is also acceptable.",
        },
    },
    {
        "id": 8,
        "difficulty": "beginner",
        "category": "crud",
        "description": "A user successfully deletes their account via a DELETE request, and there's no additional data to return. What status code is most appropriate?",
        "correct": "204",
        "options": ["204", "200", "202", "404"],
        "explanations": {
            "204": "Correct! 204 No Content means the action was successful and there's nothing to send back in the response body.",
            "200": "200 OK works if you return a confirmation message, but 204 is more appropriate when there's no response body.",
            "202": "202 Accepted would mean the deletion is queued but not yet completed.",
            "404": "404 Not Found would mean the account doesn't exist — but it did exist and was successfully deleted.",
        },
    },
    {
        "id": 26,
        "difficulty": "beginner",
        "category": "redirects",
        "description": "A user submits a login form via POST. After successful authentication, you want them to see their dashboard via GET. What redirect status code should you use?",
        "correct": "303",
        "options": ["303", "301", "302", "307"],
        "explanations": {
            "303": "Correct! 303 See Other tells the client to follow the redirect with a GET request, which is the Post/Redirect/Get pattern.",
            "301": "301 Moved Permanently is for permanent URL changes, not for post-login redirects.",
            "302": "302 Found historically changed POST to GET, but 303 is the explicit, correct choice for Post/Redirect/Get.",
            "307": "307 Temporary Redirect preserves the HTTP method, so the client would retry with POST — not what you want after login.",
        },
    },
    {
        "id": 27,
        "difficulty": "beginner",
        "category": "api-design",
        "description": "A client requests a list of products from your API, but there are no products yet. The endpoint is valid. What status code should you return?",
        "correct": "200",
        "options": ["200", "204", "404", "503"],
        "explanations": {
            "200": "Correct! 200 OK with an empty list [] is standard. The resource (product collection) exists, it just has zero items.",
            "204": "204 No Content means no body at all, but returning an empty JSON array is more useful for clients.",
            "404": "404 Not Found would mean the endpoint doesn't exist. An empty collection is not a missing resource.",
            "503": "503 Service Unavailable means the server is down. The server is fine — there's just no data yet.",
        },
    },
    {
        "id": 28,
        "difficulty": "beginner",
        "category": "errors",
        "description": "A client tries to register a username that already exists in the database. What status code should your API return?",
        "correct": "409",
        "options": ["409", "400", "422", "500"],
        "explanations": {
            "409": "Correct! 409 Conflict means the request conflicts with the current state of the resource — in this case, the username is taken.",
            "400": "400 Bad Request implies the request itself is malformed, but the request format is fine — it's a data conflict.",
            "422": "422 Unprocessable Entity is for validation errors (wrong format), not for conflicts with existing data.",
            "500": "500 is a server error. A duplicate username is an expected client-side issue, not a server bug.",
        },
    },
    {
        "id": 29,
        "difficulty": "beginner",
        "category": "headers",
        "description": "Your API only supports JSON responses, but a client sends Accept: text/xml. Your server cannot produce XML. What status code should you return?",
        "correct": "406",
        "options": ["406", "415", "400", "200"],
        "explanations": {
            "406": "Correct! 406 Not Acceptable means the server cannot produce a response matching the Accept header requirements.",
            "415": "415 Unsupported Media Type is about the request body format (Content-Type), not the response format (Accept).",
            "400": "400 Bad Request is too generic — 406 precisely communicates the issue is with content negotiation.",
            "200": "Returning 200 with JSON despite the client requesting XML would violate the Accept header contract.",
        },
    },
    {
        "id": 30,
        "difficulty": "beginner",
        "category": "crud",
        "description": "A client sends a PUT request to fully replace a user record, and the update succeeds. The server returns the updated resource. What status code should you use?",
        "correct": "200",
        "options": ["200", "201", "204", "202"],
        "explanations": {
            "200": "Correct! 200 OK with the updated resource in the body is the standard response for a successful PUT that returns the result.",
            "201": "201 Created is only appropriate if the PUT created a new resource (the URI didn't exist before).",
            "204": "204 No Content is valid if you don't return a body, but 200 is correct when you return the updated resource.",
            "202": "202 Accepted is for async processing that hasn't completed yet.",
        },
    },
    {
        "id": 31,
        "difficulty": "beginner",
        "category": "redirects",
        "description": "A short URL service receives a GET request for a shortened link. The original URL still exists. What redirect status code is most appropriate for a URL shortener?",
        "correct": "302",
        "options": ["302", "301", "307", "303"],
        "explanations": {
            "302": "Correct! 302 Found is ideal for URL shorteners — the short URL is a stable alias, but the destination could change. A temporary redirect prevents browsers from bypassing the shortener.",
            "301": "301 Moved Permanently would cause browsers to cache the redirect and skip the shortener on future visits, losing analytics.",
            "307": "307 works but is more specific (method preservation). For GET redirects, 302 is more conventional.",
            "303": "303 See Other is for redirecting after POST (PRG pattern), not for simple GET-to-GET redirects.",
        },
    },
    {
        "id": 32,
        "difficulty": "beginner",
        "category": "errors",
        "description": "A client sends a GET request for a user profile image, but the user deleted their account permanently last month. Your system tracks deletions. What status code should you return?",
        "correct": "410",
        "options": ["410", "404", "204", "301"],
        "explanations": {
            "410": "Correct! 410 Gone tells the client the resource existed but was intentionally and permanently removed. This is more informative than 404 when you know it was deleted.",
            "404": "404 Not Found works generically, but 410 is more precise when you know the resource was permanently deleted.",
            "204": "204 No Content implies success, but the client is requesting something that no longer exists.",
            "301": "301 Moved Permanently implies the resource moved somewhere else, but it was deleted entirely.",
        },
    },
    {
        "id": 33,
        "difficulty": "beginner",
        "category": "api-design",
        "description": "Your health check endpoint at /healthz is called by the load balancer every 10 seconds. The app is running fine. What status code should it return?",
        "correct": "200",
        "options": ["200", "204", "100", "202"],
        "explanations": {
            "200": "Correct! 200 OK is the standard health check response. Typically you'd include a small JSON body with status details.",
            "204": "204 No Content works but many monitoring tools expect a 200 with a body for health checks.",
            "100": "100 Continue is a provisional response for request body negotiation, not for health checks.",
            "202": "202 Accepted implies async processing. A health check should respond immediately with current status.",
        },
    },
    # --- Intermediate (17 scenarios) ---
    {
        "id": 9,
        "difficulty": "intermediate",
        "category": "crud",
        "description": "You're building a REST API. A user sends a DELETE request for a resource that was already deleted last week. What should you return?",
        "correct": "404",
        "options": ["404", "410", "204", "409"],
        "explanations": {
            "404": "Correct! 404 Not Found is the standard response — the resource doesn't exist. Unless you specifically track deletions, 404 is appropriate.",
            "410": "410 Gone is more specific and tells the client the resource was intentionally deleted. This is valid if you track deletion history, but 404 is more common.",
            "204": "204 No Content would imply the DELETE succeeded, but you shouldn't confirm deletion of something already gone.",
            "409": "409 Conflict is for state conflicts during an operation, not for missing resources.",
        },
    },
    {
        "id": 10,
        "difficulty": "intermediate",
        "category": "crud",
        "description": "Your API receives a PUT request to update a user's email, but another request is simultaneously updating the same user. The requests conflict. What status code should you return?",
        "correct": "409",
        "options": ["409", "400", "423", "500"],
        "explanations": {
            "409": "Correct! 409 Conflict indicates the request conflicts with the current state of the resource.",
            "400": "400 Bad Request implies the request itself is malformed — but the request is valid, it's the timing that's the problem.",
            "423": "423 Locked is a WebDAV status for when a resource is locked — close, but 409 is more appropriate for general conflict scenarios.",
            "500": "500 Internal Server Error implies an unexpected crash, but this is an expected concurrency issue that should be handled gracefully.",
        },
    },
    {
        "id": 11,
        "difficulty": "intermediate",
        "category": "auth",
        "description": "A client sends a request with an Authorization header, but the token has expired. The user needs to re-authenticate. What should you return?",
        "correct": "401",
        "options": ["401", "403", "419", "400"],
        "explanations": {
            "401": "Correct! 401 Unauthorized means the credentials are invalid or expired. The client should re-authenticate.",
            "403": "403 Forbidden means the server understands the request but refuses to authorize it — different from expired credentials.",
            "419": "419 is not a standard HTTP status code. Some frameworks use it for session expiry, but 401 is the correct standard code.",
            "400": "400 Bad Request is for malformed requests, not for authentication/authorization issues.",
        },
    },
    {
        "id": 12,
        "difficulty": "intermediate",
        "category": "headers",
        "description": "Your API supports JSON only, but a client sends a request with Content-Type: application/xml. What status code should you return?",
        "correct": "415",
        "options": ["415", "400", "406", "422"],
        "explanations": {
            "415": "Correct! 415 Unsupported Media Type means the server refuses to accept the request because the payload format is not supported.",
            "400": "400 Bad Request is too generic — 415 precisely communicates the issue is with the content type.",
            "406": "406 Not Acceptable is about the server not being able to produce a response matching the client's Accept header, not about the request body format.",
            "422": "422 Unprocessable Entity is for valid syntax but semantic errors in the body, not the wrong media type entirely.",
        },
    },
    {
        "id": 13,
        "difficulty": "intermediate",
        "category": "caching",
        "description": "A client sends a GET request with an If-None-Match header, and the ETag matches the current version. The resource hasn't changed. What should you return?",
        "correct": "304",
        "options": ["304", "200", "204", "412"],
        "explanations": {
            "304": "Correct! 304 Not Modified tells the client to use its cached copy — the resource hasn't changed since last fetched.",
            "200": "200 OK with the full body would work but wastes bandwidth. 304 is designed exactly for this caching scenario.",
            "204": "204 No Content means success with no body, but it doesn't convey the caching semantics that 304 does.",
            "412": "412 Precondition Failed is for when conditions in headers like If-Match fail, not If-None-Match cache checks.",
        },
    },
    {
        "id": 14,
        "difficulty": "intermediate",
        "category": "errors",
        "description": "Your server is undergoing scheduled maintenance and will be back in 2 hours. What status code should you return to all incoming requests?",
        "correct": "503",
        "options": ["503", "500", "502", "504"],
        "explanations": {
            "503": "Correct! 503 Service Unavailable indicates the server is temporarily unable to handle requests, often due to maintenance. Include a Retry-After header!",
            "500": "500 Internal Server Error implies an unexpected crash, not planned maintenance.",
            "502": "502 Bad Gateway means a proxy received an invalid response from upstream — not the same as planned downtime.",
            "504": "504 Gateway Timeout means a proxy didn't get a timely response from upstream — not relevant to maintenance.",
        },
    },
    {
        "id": 15,
        "difficulty": "intermediate",
        "category": "auth",
        "description": "A logged-in regular user tries to access the admin-only settings page. They are authenticated but don't have admin privileges. What should you return?",
        "correct": "403",
        "options": ["403", "401", "404", "405"],
        "explanations": {
            "403": "Correct! 403 Forbidden means the server knows who the user is but they don't have permission to access this resource.",
            "401": "401 Unauthorized is for missing or invalid authentication. This user IS authenticated, just not authorized.",
            "404": "404 Not Found could be used to hide the endpoint from unauthorized users, but 403 is semantically correct.",
            "405": "405 Method Not Allowed is about using the wrong HTTP method (e.g., POST instead of GET), not about permissions.",
        },
    },
    {
        "id": 16,
        "difficulty": "intermediate",
        "category": "api-design",
        "description": "A client makes too many API requests and hits your rate limit. What status code should you return?",
        "correct": "429",
        "options": ["429", "403", "503", "400"],
        "explanations": {
            "429": "Correct! 429 Too Many Requests tells the client they've sent too many requests in a given time period. Include a Retry-After header.",
            "403": "403 Forbidden could work but doesn't communicate that the issue is rate limiting specifically.",
            "503": "503 Service Unavailable implies the whole service is down, not just that one client is being throttled.",
            "400": "400 Bad Request implies something is wrong with the request itself, not with how many requests were sent.",
        },
    },
    {
        "id": 17,
        "difficulty": "intermediate",
        "category": "api-design",
        "description": "Your API receives a long-running report generation request. You want to acknowledge receipt and process it in the background. What status code should you return?",
        "correct": "202",
        "options": ["202", "200", "201", "204"],
        "explanations": {
            "202": "Correct! 202 Accepted means the request has been accepted for processing, but the processing is not yet complete.",
            "200": "200 OK implies the request is fully completed — misleading for an async operation that hasn't finished yet.",
            "201": "201 Created implies the resource is already created, but it's still being generated.",
            "204": "204 No Content doesn't communicate that something is happening in the background.",
        },
    },
    {
        "id": 34,
        "difficulty": "intermediate",
        "category": "caching",
        "description": "A client downloads a large video file and wants to resume after a network interruption. It sends a Range header requesting bytes 500000-999999. The server supports range requests and the range is valid. What status code should the server return?",
        "correct": "206",
        "options": ["206", "200", "416", "304"],
        "explanations": {
            "206": "Correct! 206 Partial Content is the response for a successful range request, returning only the requested byte range with a Content-Range header.",
            "200": "200 OK would mean sending the entire file, ignoring the Range header and wasting bandwidth.",
            "416": "416 Range Not Satisfiable is for when the requested range is invalid or beyond the file size.",
            "304": "304 Not Modified is for cache validation, not for partial content delivery.",
        },
    },
    {
        "id": 35,
        "difficulty": "intermediate",
        "category": "redirects",
        "description": "A POST endpoint for creating orders has moved to a new URL. You want clients to re-send their POST request (with the body) to the new URL. What redirect status code should you use?",
        "correct": "307",
        "options": ["307", "301", "302", "303"],
        "explanations": {
            "307": "Correct! 307 Temporary Redirect guarantees the HTTP method is preserved. The client will re-send the POST to the new URL.",
            "301": "301 Moved Permanently historically allows clients to change POST to GET, which would lose the request body.",
            "302": "302 Found also historically changed POST to GET in most browsers, which would lose the request body.",
            "303": "303 See Other explicitly tells the client to follow up with GET — the opposite of what you want.",
        },
    },
    {
        "id": 36,
        "difficulty": "intermediate",
        "category": "redirects",
        "description": "Your API has permanently moved a POST endpoint from /api/v1/orders to /api/v2/orders. You want clients to always use the new URL and preserve the POST method. What status code should you use?",
        "correct": "308",
        "options": ["308", "301", "307", "302"],
        "explanations": {
            "308": "Correct! 308 Permanent Redirect is permanent (like 301) but preserves the HTTP method (like 307). Perfect for permanently relocated POST endpoints.",
            "301": "301 Moved Permanently may cause clients to change POST to GET, losing the request body.",
            "307": "307 Temporary Redirect preserves the method but signals the move is temporary. Use 308 for permanent moves.",
            "302": "302 Found is temporary and may change the method from POST to GET.",
        },
    },
    {
        "id": 37,
        "difficulty": "intermediate",
        "category": "errors",
        "description": "A client sends a POST to create a user with a valid JSON body, but the 'age' field is -5, which fails your business rules. The JSON is syntactically correct. What status code should you return?",
        "correct": "422",
        "options": ["422", "400", "409", "500"],
        "explanations": {
            "422": "Correct! 422 Unprocessable Entity means the request body is syntactically valid but semantically incorrect — the data fails business validation.",
            "400": "400 Bad Request is for malformed requests (invalid JSON, missing fields). The JSON is valid here; the issue is the value.",
            "409": "409 Conflict is for conflicts with existing state, not for invalid field values.",
            "500": "500 is a server error. Validation failures are client errors that should never return 5xx.",
        },
    },
    {
        "id": 38,
        "difficulty": "intermediate",
        "category": "caching",
        "description": "A client sends a conditional PUT with If-Match and the current ETag. The ETag matches and the update succeeds. What status code should the server return?",
        "correct": "200",
        "options": ["200", "204", "304", "412"],
        "explanations": {
            "200": "Correct! The precondition passed and the update succeeded. 200 OK with the updated resource (and new ETag) is the standard response.",
            "204": "204 No Content is also valid if you don't return a body, but returning the updated resource with the new ETag is best practice.",
            "304": "304 Not Modified is for GET cache validation, not for successful PUT updates.",
            "412": "412 Precondition Failed would mean the ETag didn't match — but it did match in this scenario.",
        },
    },
    {
        "id": 39,
        "difficulty": "intermediate",
        "category": "headers",
        "description": "A client sends a request with Accept-Encoding: gzip, br. Your server supports both. Which compression should you use, and what header must you include in the response?",
        "correct": "200",
        "options": ["200", "406", "415", "304"],
        "explanations": {
            "200": "Correct! Return 200 OK with the Content-Encoding header set to your chosen compression (e.g., br for Brotli). The Vary: Accept-Encoding header should also be included for caching.",
            "406": "406 Not Acceptable would mean you can't serve any acceptable format, but you support both gzip and br.",
            "415": "415 Unsupported Media Type is about the request body's Content-Type, not about response encoding.",
            "304": "304 Not Modified is for cache validation, not for content encoding negotiation.",
        },
    },
    {
        "id": 40,
        "difficulty": "intermediate",
        "category": "api-design",
        "description": "Your API receives a request for GET /api/v1/users, but you've sunset v1 and only support v2 now. What status code should you return?",
        "correct": "410",
        "options": ["410", "404", "301", "426"],
        "explanations": {
            "410": "Correct! 410 Gone tells the client that this version of the API has been intentionally and permanently retired.",
            "404": "404 Not Found works but doesn't communicate that the endpoint once existed and was deliberately removed.",
            "301": "301 Moved Permanently with a redirect to v2 could work, but the API contract may differ between versions, causing client errors.",
            "426": "426 Upgrade Required is for protocol upgrades (like HTTP to WebSocket), not API version changes.",
        },
    },
    {
        "id": 41,
        "difficulty": "intermediate",
        "category": "auth",
        "description": "A client sends a request with a valid API key, but the key only grants read access. They attempt a DELETE operation. What status code should you return?",
        "correct": "403",
        "options": ["403", "401", "405", "400"],
        "explanations": {
            "403": "Correct! 403 Forbidden means the client is authenticated (valid key) but lacks the required permissions for this operation.",
            "401": "401 Unauthorized is for invalid or missing credentials. This key is valid — it just doesn't have write permissions.",
            "405": "405 Method Not Allowed means the endpoint doesn't support DELETE at all. Here it does, just not for this key's scope.",
            "400": "400 Bad Request is for malformed requests, not authorization failures.",
        },
    },
    # --- Expert (18 scenarios) ---
    {
        "id": 18,
        "difficulty": "expert",
        "category": "headers",
        "description": "You're implementing a file upload endpoint. A client sends a POST request with a Content-Length of 50GB, which exceeds your server's limit. What status code should you return before the client finishes uploading?",
        "correct": "413",
        "options": ["413", "400", "507", "431"],
        "explanations": {
            "413": "Correct! 413 Payload Too Large tells the client the request body exceeds the server's defined limit.",
            "400": "400 Bad Request is too generic and doesn't tell the client specifically that the payload is too large.",
            "507": "507 Insufficient Storage is a WebDAV status about the server running out of storage — different from rejecting a too-large request.",
            "431": "431 Request Header Fields Too Large is about headers being too large, not the request body.",
        },
    },
    {
        "id": 19,
        "difficulty": "expert",
        "category": "caching",
        "description": "A client sends a PATCH request to update a resource, but uses the If-Match header with an outdated ETag. The resource has been modified since the client last fetched it. What should you return?",
        "correct": "412",
        "options": ["412", "409", "304", "428"],
        "explanations": {
            "412": "Correct! 412 Precondition Failed means the condition specified in the If-Match header evaluated to false — the ETag doesn't match.",
            "409": "409 Conflict is for logical conflicts in the request, but 412 is specifically designed for conditional request failures.",
            "304": "304 Not Modified is for cache validation with If-None-Match on GET requests, not for conditional writes.",
            "428": "428 Precondition Required means the server requires a conditional request — but the client DID send one, it just failed.",
        },
    },
    {
        "id": 20,
        "difficulty": "expert",
        "category": "errors",
        "description": "Your reverse proxy receives a request and forwards it to the backend server, but the backend returns a malformed HTTP response. What status code should the proxy return to the client?",
        "correct": "502",
        "options": ["502", "500", "503", "504"],
        "explanations": {
            "502": "Correct! 502 Bad Gateway means the proxy received an invalid response from the upstream server.",
            "500": "500 Internal Server Error implies the proxy itself crashed, not that it received a bad upstream response.",
            "503": "503 Service Unavailable means the service is temporarily down — not that an invalid response was received.",
            "504": "504 Gateway Timeout means the upstream server didn't respond in time — but here it did respond, just with garbage.",
        },
    },
    {
        "id": 21,
        "difficulty": "expert",
        "category": "api-design",
        "description": "A client sends a request to your API which only accepts GET and POST, but they use a PUT method. What status code should you return?",
        "correct": "405",
        "options": ["405", "400", "404", "501"],
        "explanations": {
            "405": "Correct! 405 Method Not Allowed means the HTTP method is not supported for this endpoint. Include an Allow header listing valid methods.",
            "400": "400 Bad Request implies the request is malformed, but the issue is specifically the HTTP method.",
            "404": "404 Not Found implies the URL doesn't exist — but it does, just not for PUT.",
            "501": "501 Not Implemented means the server doesn't support the method at all (for any endpoint), not just this specific resource.",
        },
    },
    {
        "id": 22,
        "difficulty": "expert",
        "category": "headers",
        "description": "You're implementing WebSocket support. A client sends an HTTP/1.1 Upgrade request with Connection: Upgrade and Upgrade: websocket, and your server accepts the protocol switch. What status code should you return?",
        "correct": "101",
        "options": ["101", "200", "426", "100"],
        "explanations": {
            "101": "Correct! 101 Switching Protocols indicates the server is switching to the protocol specified in the Upgrade header (WebSocket).",
            "200": "200 OK doesn't indicate a protocol switch is happening — the client would remain on HTTP.",
            "426": "426 Upgrade Required means the server DEMANDS a protocol upgrade, not that it's accepting one.",
            "100": "100 Continue tells the client to proceed with the request body, not that a protocol switch is occurring.",
        },
    },
    {
        "id": 23,
        "difficulty": "expert",
        "category": "errors",
        "description": "A government orders you to take down a specific page due to a legal demand. You want to communicate to users that the content was removed for legal reasons. What status code is most appropriate?",
        "correct": "451",
        "options": ["451", "403", "410", "404"],
        "explanations": {
            "451": "Correct! 451 Unavailable For Legal Reasons (named after Fahrenheit 451) indicates the resource is unavailable due to legal demands.",
            "403": "403 Forbidden is generic and doesn't explain WHY access is denied.",
            "410": "410 Gone means the resource was removed but doesn't communicate the legal reason.",
            "404": "404 Not Found pretends the resource never existed — 451 is more transparent about censorship.",
        },
    },
    {
        "id": 24,
        "difficulty": "expert",
        "category": "caching",
        "description": "Your API requires all write requests to include an If-Match header for optimistic concurrency control, but a client sends a PUT request without it. What should you return?",
        "correct": "428",
        "options": ["428", "412", "400", "409"],
        "explanations": {
            "428": "Correct! 428 Precondition Required tells the client that the server requires the request to be conditional (include If-Match).",
            "412": "412 Precondition Failed is for when a precondition WAS sent but evaluated to false. Here, no precondition was sent at all.",
            "400": "400 Bad Request is too generic — 428 specifically communicates that a conditional header is required.",
            "409": "409 Conflict is for request conflicts with the current resource state, not for missing conditional headers.",
        },
    },
    {
        "id": 25,
        "difficulty": "expert",
        "category": "headers",
        "description": "A client requests a range of bytes from a large video file using the Range header, but the requested range is beyond the end of the file. What status code should you return?",
        "correct": "416",
        "options": ["416", "400", "404", "206"],
        "explanations": {
            "416": "Correct! 416 Range Not Satisfiable means the range specified in the Range header can't be fulfilled — it's outside the resource's bounds.",
            "400": "400 Bad Request is too vague — 416 specifically addresses invalid range requests.",
            "404": "404 Not Found means the resource doesn't exist — but it does, the requested byte range is just invalid.",
            "206": "206 Partial Content is the success response for a valid range request, not for an invalid range.",
        },
    },
    {
        "id": 42,
        "difficulty": "expert",
        "category": "crud",
        "description": "A client sends a PUT request to update a document, using an If-Match header with an ETag for optimistic locking. Another user modified the document moments ago, so the ETag no longer matches. Your API should reject the update. What status code?",
        "correct": "412",
        "options": ["412", "409", "428", "400"],
        "explanations": {
            "412": "Correct! 412 Precondition Failed is exactly for this case — the If-Match precondition evaluated to false because the ETag changed.",
            "409": "409 Conflict is for general state conflicts. 412 is the precise code when a conditional header (If-Match) fails.",
            "428": "428 Precondition Required is for when the client forgot to send the precondition. Here they sent it; it just didn't match.",
            "400": "400 Bad Request is for malformed requests. The request is perfectly formed; the precondition simply failed.",
        },
    },
    {
        "id": 43,
        "difficulty": "expert",
        "category": "auth",
        "description": "You're building a multi-step API flow. A client authenticates (gets a token), then uses the token to request admin access. The token is valid but the user's account has been suspended. What status code should you return?",
        "correct": "403",
        "options": ["403", "401", "423", "451"],
        "explanations": {
            "403": "Correct! 403 Forbidden — the user is authenticated (valid token) but their suspended account means they're not authorized to access any resources.",
            "401": "401 Unauthorized means bad credentials. The token is valid; the account status is the problem.",
            "423": "423 Locked is a WebDAV status and implies a resource is locked, not that a user account is suspended.",
            "451": "451 Unavailable For Legal Reasons is for legal takedowns, not account suspensions.",
        },
    },
    {
        "id": 44,
        "difficulty": "expert",
        "category": "api-design",
        "description": "A client sends a GraphQL query over HTTP POST to your /graphql endpoint. The HTTP request is valid, but the GraphQL query references a field that doesn't exist in the schema. What HTTP status code should you return?",
        "correct": "200",
        "options": ["200", "400", "422", "404"],
        "explanations": {
            "200": "Correct! Per the GraphQL over HTTP spec, the server should return 200 OK with errors in the JSON body's 'errors' array. HTTP status reflects transport success, not query-level errors.",
            "400": "400 is only appropriate if the request itself is malformed (invalid JSON, wrong Content-Type). A valid HTTP request with an invalid query still gets 200.",
            "422": "422 might seem logical, but GraphQL convention is to use the response body's errors array for query validation failures.",
            "404": "404 would mean the /graphql endpoint doesn't exist. The endpoint is fine; the query has errors.",
        },
    },
    {
        "id": 45,
        "difficulty": "expert",
        "category": "headers",
        "description": "Your API receives a request with Accept: application/vnd.myapp.v2+json. You only support v1 and v3 of the vendor media type. What status code should you return?",
        "correct": "406",
        "options": ["406", "415", "400", "404"],
        "explanations": {
            "406": "Correct! 406 Not Acceptable means the server cannot produce a response matching the Accept header. The requested API version via content negotiation is not available.",
            "415": "415 Unsupported Media Type is about the request body's Content-Type, not the Accept header for versioning.",
            "400": "400 Bad Request is too generic. The request is well-formed; the server just can't satisfy the Accept requirement.",
            "404": "404 Not Found would mean the URL doesn't exist. The URL is fine; the version requested via Accept is unavailable.",
        },
    },
    {
        "id": 46,
        "difficulty": "expert",
        "category": "api-design",
        "description": "Your webhook endpoint receives a POST from a payment provider. The payload signature in the X-Signature header doesn't match your computed HMAC. What status code should you return?",
        "correct": "401",
        "options": ["401", "403", "400", "422"],
        "explanations": {
            "401": "Correct! 401 Unauthorized — the signature is the authentication mechanism for webhooks. An invalid signature means failed authentication.",
            "403": "403 Forbidden implies the sender is known but not allowed. Here the sender's identity couldn't be verified.",
            "400": "400 Bad Request implies the request format is wrong. The format is fine; the cryptographic signature is invalid.",
            "422": "422 Unprocessable Entity is for semantic validation errors, not authentication failures.",
        },
    },
    {
        "id": 47,
        "difficulty": "expert",
        "category": "errors",
        "description": "Your API gateway forwards a request to a microservice, but the microservice takes too long and the gateway's timeout expires. What status code should the gateway return?",
        "correct": "504",
        "options": ["504", "502", "503", "408"],
        "explanations": {
            "504": "Correct! 504 Gateway Timeout means the gateway didn't receive a timely response from the upstream server.",
            "502": "502 Bad Gateway means the upstream responded with an invalid response. Here it didn't respond at all (timeout).",
            "503": "503 Service Unavailable means the gateway itself is overloaded. The issue is with the upstream service's response time.",
            "408": "408 Request Timeout is about the client being too slow to send its request to the server, not about upstream timeouts.",
        },
    },
    {
        "id": 48,
        "difficulty": "expert",
        "category": "api-design",
        "description": "A client subscribes to a Server-Sent Events (SSE) stream at /events. The connection is established and the server begins streaming events. What status code should the initial response have?",
        "correct": "200",
        "options": ["200", "202", "101", "204"],
        "explanations": {
            "200": "Correct! SSE uses a standard 200 OK response with Content-Type: text/event-stream. Unlike WebSocket, SSE operates over regular HTTP.",
            "202": "202 Accepted implies async processing where the client polls later. SSE is a live stream, not deferred processing.",
            "101": "101 Switching Protocols is for WebSocket, not SSE. SSE stays on HTTP and doesn't switch protocols.",
            "204": "204 No Content means no body, but SSE streams data continuously in the response body.",
        },
    },
    {
        "id": 49,
        "difficulty": "expert",
        "category": "auth",
        "description": "During an OAuth 2.0 flow, the authorization server detects that the redirect_uri in the request doesn't match any registered callback URL. What HTTP status code should the authorization server return?",
        "correct": "400",
        "options": ["400", "403", "302", "401"],
        "explanations": {
            "400": "Correct! Per RFC 6749, the authorization server must NOT redirect to an unregistered URI. It should return 400 Bad Request directly to the user-agent, explaining the error.",
            "403": "403 Forbidden implies the client is known but unauthorized. The issue is a malformed/mismatched parameter, not permissions.",
            "302": "302 redirecting to the mismatched URI would be a security vulnerability — never redirect to an unvalidated callback URL.",
            "401": "401 Unauthorized is for authentication failures. The redirect_uri mismatch is a request validation issue.",
        },
    },
    {
        "id": 50,
        "difficulty": "expert",
        "category": "headers",
        "description": "A client sends a request with a very long Cookie header (32KB) that exceeds your server's header size limit. What status code should you return?",
        "correct": "431",
        "options": ["431", "413", "400", "414"],
        "explanations": {
            "431": "Correct! 431 Request Header Fields Too Large is specifically for when headers (like Cookie) are too large for the server to process.",
            "413": "413 Payload Too Large is for the request body being too large, not the headers.",
            "400": "400 Bad Request is too generic — 431 precisely identifies the header size issue.",
            "414": "414 URI Too Long is for when the URL itself is too long, not the headers.",
        },
    },
    {
        "id": 51,
        "difficulty": "expert",
        "category": "api-design",
        "description": "A client sends a PATCH request with Content-Type: application/json-patch+json containing an 'op: test' operation that fails. The test operation verifies a value before applying changes. What status code should you return?",
        "correct": "409",
        "options": ["409", "412", "422", "400"],
        "explanations": {
            "409": "Correct! Per RFC 6902, when a JSON Patch 'test' operation fails, the server should return 409 Conflict because the resource state doesn't match the expected value.",
            "412": "412 Precondition Failed is for HTTP conditional headers (If-Match), not for JSON Patch test operations within the body.",
            "422": "422 would imply the patch document is semantically invalid, but the patch is valid — the test just found the value doesn't match.",
            "400": "400 would mean the patch document is malformed. The patch is well-formed; it's a state conflict.",
        },
    },
]
